# -*- coding: utf-8 -*-
"""01_PythonBasics_02032022.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15CTPILQWsevbBHb9fsjLgjFjXz5QItKY
"""

print('Hello World!')

print

print()

print("Hello world')

print("Hello world')")

print("My name is Andrew 
    it is nice to be here
    this is a very good lesson")

print("""My name is Andrew 
it is nice to be here
this is a very good lesson""")

print('''My name is Andrew 
it is nice to be here
this is a very good lesson''')

print(```My name is Andrew 
it is nice to be here
this is a very good lesson```)

print('''My name is Andrew 
it is nice to be here
this is a very good lesson
this is the fourth line''')

print('''My name is Andrew 'I'm so happy'
it is nice to be here
this is a very good lesson
this is the fourth line''')

print("""My name is Andrew "I'm so happy"
it is nice to be here
this is a very good lesson
this is the fourth line""")

print("""My name is Andrew "I'm so happy"

  it is nice to be here
      this is a very good lesson
        this is the fourth line""")

print(type(3.14))

print(type("3.14"))

"test"
"text"

print(''''We should have enough time for our family"''')

print()
print('')

print()
print('''')

"""single quote  ' ''  '''
double qute "    ""   '''    

'''' not equal to ""
"""

# single quote  ' ''  '''
# double qute "    ""   """    

# '''' not equal to ""

print("hello")  # this is an inline comment

print("hello")#this is an inline comment

print("hello")
# this is single line comment

# this is first line
# this is second line
# this is third line

3.14
"3.14"

"3.14"
3.14

print(3 + 5)

3 + 5

print("3" + 5)

print("3" + "5")

"3" + "5"

